"""Offline generator: python3 generate-url-idna.py <Ada v2.9.2 src/ada_idna.cpp>.
No download, compilation, Node or runtime dependency. Input digest is pinned.
Derived data and compatibility semantics: see ADA-LICENSE and UNICODE-LICENSE.
"""
from pathlib import Path
import hashlib
import re
import sys
source = Path(sys.argv[1]).read_bytes()
expected = '1b9af936cdb63fb295c61e9444fee89e0b565205f8002fb40425fcaae5d544b7'
if hashlib.sha256(source).hexdigest() != expected:
    raise SystemExit('ada_2_9_2_source_digest_mismatch')
s = source.decode()
def array(name):
    body = re.search(r'uint32_t ' + name + r'\[\] = \{(.*?)\};', s, re.S)[1]
    return [(int(n, 16), int(n, 16)) for n in re.findall(r'0x[0-9a-fA-F]+', body)]
def charset(ranges):
    merged = []
    scalar_ranges = [(max(a, lo), min(b, hi)) for a, b in ranges for lo, hi in [(1, 0xd7ff), (0xe000, 0x10ffff)] if max(a, lo) <= min(b, hi)]
    for a, b in sorted(scalar_ranges):
        a = max(a, 1)
        if a > b: continue
        if merged and a <= merged[-1][1] + 1: merged[-1] = (merged[-1][0], max(b, merged[-1][1]))
        else: merged.append((a, b))
    def esc(n): return '\\' + (f'{n:04X}' if n <= 65535 else f'+{n:06X}')
    return '[' + ''.join(esc(a) + ('-' + esc(b) if a != b else '') for a, b in merged) + ']'
table = s[s.index('const uint32_t table['):s.index('/* end file src/mapping_tables.cpp */')]
entries = [(int(a), int(b)) for a,b in re.findall(r'\{(\d+),\s*(\d+)\}',table)]
directions = [(int(a,16),int(b,16),c) for a,b,c in re.findall(r'\{(0x[0-9a-f]+),\s*(0x[0-9a-f]+),\s*direction::(\w+)\}',s)]
def bidi(*types): return [(a,b) for a,b,c in directions if c in types]
sets = {
 'valid': [(a, entries[i+1][0]-1 if i+1<len(entries) else 0x10ffff) for i,(a,d) in enumerate(entries) if d==1],
 'mark': array('combining'), 'virama': array('virama'),
 'rtl': bidi('R','AL','AN'), 'ltr_first': bidi('L'),
 'ltr_allowed': bidi('L','EN','ES','CS','ET','ON','BN','NSM'),
 'rtl_allowed': bidi('R','AL','AN','EN','ES','CS','ET','ON','BN','NSM'),
 'rtl_last': bidi('R','AL','EN','AN'), 'nsm': bidi('NSM'), 'en': bidi('EN'), 'an': bidi('AN'),
 'joining_left': array('L')+array('D'), 'joining_right': array('R')+array('D'),
}
header = f'''-- Generated by generate-url-idna.py; independent local SQL codec only.
-- Pinned canonical Node22 URL engine: Ada 2.9.2 (IDNA mapping 15.0.0).
-- Source: https://raw.githubusercontent.com/ada-url/ada/v2.9.2/src/ada_idna.cpp
-- SHA256 {expected}
-- See ADA-LICENSE.txt and UNICODE-LICENSE.txt. No application/runtime import.
'''
sql = header + "CREATE FUNCTION official_provenance_private.url_unicode_set(kind text) RETURNS text LANGUAGE sql IMMUTABLE STRICT SET search_path='' AS $sets$ SELECT CASE kind\n"
for name, ranges in sets.items(): sql += f" WHEN '{name}' THEN U&'{charset(ranges)}'\n"
sql += ' END $sets$;\n'
Path(__file__).with_name('url-idna-data.sql').write_text(sql)
