import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { describe, test } from 'node:test'
import assert from 'node:assert/strict'
import { fileURLToPath } from 'node:url'

const hier = dirname(fileURLToPath(import.meta.url))
const komponente = readFileSync(join(hier, '../../components/account/SecuritySitzung.tsx'), 'utf8')
const seite = readFileSync(join(hier, '../../app/account/security/page.tsx'), 'utf8')
const settings = readFileSync(join(hier, '../../app/account/settings/page.tsx'), 'utf8')
const logout = readFileSync(join(hier, '../../components/account/SecurityLogout.tsx'), 'utf8')
const logoutLogik = readFileSync(join(hier, './account-logout-scopes.ts'), 'utf8')
const logoutAktion = readFileSync(join(hier, '../../app/account/security/logout-action.ts'), 'utf8')
const mfa = readFileSync(join(hier, '../../components/account/SecurityMFA.tsx'), 'utf8')
const stepUp = readFileSync(join(hier, './account-mfa-step-up.ts'), 'utf8')
const logik = readFileSync(join(hier, './account-session-view.ts'), 'utf8')
const allgemein = readFileSync(join(hier, '../../app/auth/sign-out.ts'), 'utf8')
const proxy = readFileSync(join(hier, '../../proxy.ts'), 'utf8')
const config = readFileSync(join(hier, '../../supabase/config.toml'), 'utf8')

describe('AP-5-S5 Vertrag und Accessibility', () => {
  test('Security-Seite zeigt die ehrliche Sessionkarte und keine Listing-Route', () => {
    assert.equal(seite.includes('SecuritySitzung'), true)
    assert.equal(seite.includes('SecurityLogout'), true)
    assert.equal(settings.includes('aktuelle Sitzung'), true)
    assert.equal(seite.includes('listSessions'), false)
    assert.equal(seite.includes('getSessions'), false)
    assert.equal(seite.includes('/account/sessions'), false)
    assert.equal(komponente.includes('data-andere-sitzungen={zustand.andere}'), true)
    assert.equal(komponente.includes('ANDERE_SITZUNGEN_TEXT'), true)
    assert.equal(logik.includes("andere: 'unsupported'") || logik.includes('andere: SITZUNG_ANDERE_LAGE'), true)
    assert.equal(logik.includes('andereSitzungenAnzahl'), true)
    assert.equal(logik.includes('return null'), true)
    assert.equal(komponente.includes('0 Geräte'), false)
    assert.equal(komponente.includes('0 andere'), false)
    assert.equal(logik.includes('0 Geräte'), false)
  })

  test('keine privilegierte Sessionliste und keine Fake-leeren Geräte', () => {
    assert.equal(/\.listSessions\s*\(|auth\.getSessions\s*\(/.test(logik), false)
    assert.equal(/\.from\(\s*['"]sessions['"]/.test(logik), false)
    assert.equal(/auth\.sessions/.test(logik), false)
    assert.equal(/\.listSessions\s*\(|auth\.getSessions\s*\(/.test(komponente), false)
    assert.equal(komponente.includes('createAdminClient'), false)
    assert.equal(logik.includes('service_role'), false)
    assert.equal(komponente.includes('service_role'), false)
    assert.equal(komponente.includes('<ul'), false)
    assert.equal(komponente.includes('skeleton'), false)
    assert.equal(logik.includes('Product-Owner') || logik.includes('unsupported, niemals empty'), true)
  })

  test('keine rohen Session-, Token-, Cookie- oder User-Agent-Daten in der UI', () => {
    assert.equal(komponente.includes('session_id'), false)
    assert.equal(komponente.includes('access_token'), false)
    assert.equal(komponente.includes('refresh_token'), false)
    assert.equal(komponente.includes('navigator.userAgent'), true)
    assert.equal(komponente.includes('{navigator.userAgent}'), false)
    assert.equal(komponente.includes('userAgent}'), false)
    assert.equal(komponente.includes('expires_at'), true)
    assert.equal(komponente.includes('data.session.expires_at'), true)
    assert.equal(komponente.includes('data.session.access_token'), false)
    assert.equal(komponente.includes('console.log'), false)
    assert.equal(logik.includes('console.log'), false)
    assert.equal(logik.includes('cookie'), true)
    assert.equal(logik.includes('LEAK_MUSTER'), true)
    assert.equal(komponente.includes('LOKAL_HINWEIS_LABEL') || komponente.includes('zustand.lokal.text'), true)
    assert.equal(logik.includes('Lokal erkannt, nicht serverseitig als Geräteidentität geprüft'), true)
    assert.equal(komponente.includes('verifiziert'), false)
    assert.equal(logik.includes('dieses Gerät ist verifiziert'), false)
  })

  test('S3-Logout-Scopes und S4-MFA-Reconcile bleiben getrennte Authorities', () => {
    assert.equal(logout.includes('id="account-abmelden"'), true)
    assert.equal(komponente.includes('SITZUNG_ABMELDEN_ANKER'), true)
    assert.equal(komponente.includes('accountLogoutScopeAction'), false)
    assert.equal(komponente.includes("scope: 'local'"), false)
    assert.equal(komponente.includes("scope: 'others'"), false)
    assert.equal(komponente.includes("scope: 'global'"), false)
    assert.equal(logoutLogik.includes("['local', 'others', 'global']"), true)
    assert.equal(logoutAktion.includes('signOut({ scope: options.scope })'), true)
    assert.equal(allgemein.includes('await supabase.auth.signOut()'), true)
    assert.equal(allgemein.includes('scope:'), false)
    assert.equal(stepUp.includes('refreshSession'), true)
    assert.equal(stepUp.includes("currentLevel === 'aal2'"), true)
    assert.equal(mfa.includes('mfaUnenrollVorbereiten'), true)
    assert.equal(mfa.includes('mfaStepUpUndUnenroll'), true)
    assert.equal(komponente.includes('mfa.unenroll'), false)
    assert.equal(komponente.includes('mfa.challenge'), false)
    assert.equal(proxy.includes("currentLevel === 'aal2'"), false)
    assert.match(config, /enroll_enabled\s*=\s*true/)
  })

  test('Busy-, Error- und Unsupported-Zustände sind zugänglich getrennt', () => {
    assert.equal(komponente.includes('aria-busy={beschaeftigt}'), true)
    assert.equal(komponente.includes('role={zustand.lage === "error" || zustand.lage === "unavailable" ? "alert" : "status"}'), true)
    assert.equal(komponente.includes('"assertive"'), true)
    assert.equal(komponente.includes('"polite"'), true)
    assert.equal(komponente.includes('min-h-11'), true)
    assert.equal(komponente.includes('aria-labelledby="account-andere-sitzungen-title"'), true)
    assert.equal(komponente.includes('CardTitle as="h2"'), true)
    assert.equal(logik.includes("'loading' | 'current' | 'unavailable' | 'unsupported' | 'error'"), true)
    assert.equal(logik.includes('sitzungIstBeschaeftigt'), true)
  })
})
