import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { describe, test } from 'node:test'
import assert from 'node:assert/strict'
import { fileURLToPath } from 'node:url'

const hier = dirname(fileURLToPath(import.meta.url))
const mfa = readFileSync(join(hier, '../../components/account/SecurityMFA.tsx'), 'utf8')
const dialog = readFileSync(join(hier, '../../components/account/SecurityMfaStepUp.tsx'), 'utf8')
const logik = readFileSync(join(hier, './account-mfa-step-up.ts'), 'utf8')
const seite = readFileSync(join(hier, '../../app/account/security/page.tsx'), 'utf8')
const logout = readFileSync(join(hier, '../../components/account/SecurityLogout.tsx'), 'utf8')
const passwort = readFileSync(join(hier, '../../components/account/SecurityPasswort.tsx'), 'utf8')
const login = readFileSync(join(hier, '../../components/auth/LoginForm.tsx'), 'utf8')
const admin = readFileSync(join(hier, './admin-aal.ts'), 'utf8')
const proxy = readFileSync(join(hier, '../../proxy.ts'), 'utf8')
const config = readFileSync(join(hier, '../../supabase/config.toml'), 'utf8')

describe('AP-5-S4 Vertrag und Accessibility', () => {
  test('verified Unenroll nutzt challenge/verify und AAL-Recheck', () => {
    assert.equal(mfa.includes('mfaUnenrollVorbereiten'), true)
    assert.equal(mfa.includes('mfaStepUpUndUnenroll'), true)
    assert.equal(mfa.includes('mfaUnenrollDirekt'), true)
    assert.equal(mfa.includes('SecurityMfaStepUp'), true)
    assert.equal(logik.includes('getAuthenticatorAssuranceLevel'), true)
    assert.equal(logik.includes('aalIstAusreichendFuerVerifiedUnenroll'), true)
    assert.equal(logik.includes("currentLevel === 'aal2'"), true)
    assert.equal(logik.includes('mfa.challenge'), true)
    assert.equal(logik.includes('mfa.verify'), true)
    assert.equal(logik.includes('mfa.unenroll'), true)
    assert.equal(logik.includes('startTotpChallenge'), false)
    assert.equal(logik.includes('challengeAndVerify'), false)
    assert.equal(mfa.includes('startTotpChallenge'), false)
  })

  test('Enroll, Recovery, Reauth und Admin-AAL2 bleiben getrennte Authorities', () => {
    assert.equal(mfa.includes('mfa.enroll'), true)
    assert.equal(mfa.includes('reauthenticate'), false)
    assert.equal(mfa.includes('nonce'), false)
    assert.equal(mfa.includes('accountLogoutScopeAction'), true)
    assert.equal(mfa.includes('accountLogoutScopeAction("local")') || mfa.includes("accountLogoutScopeAction('local')"), true)
    assert.equal(mfa.includes('refreshSession'), true)
    assert.equal(logik.includes('refreshSession'), true)
    assert.equal(logik.includes("scope: 'local'"), true)
    assert.equal(mfa.includes('mfaStepUpSollLokalenAuthVerlassen'), true)
    assert.equal(passwort.includes('mfaUnenrollVorbereiten'), false)
    assert.equal(logout.includes('mfaUnenrollVorbereiten'), false)
    assert.equal(login.includes('MFATotpDialog'), true)
    assert.equal(login.includes('mfaUnenrollVorbereiten'), false)
    assert.equal(admin.includes('istAktuellesAal2'), true)
    assert.equal(admin.includes('ADMIN_STEP_UP_PFAD'), true)
    assert.equal(admin.includes('mfaUnenrollVorbereiten'), false)
    assert.equal(proxy.includes('getAuthenticatorAssuranceLevel'), false)
  })

  test('Dialog hat Fokus, Busy-State und one-time-code', () => {
    assert.equal(dialog.includes('role="dialog"'), true)
    assert.equal(dialog.includes('aria-modal="true"'), true)
    assert.equal(dialog.includes('aria-labelledby='), true)
    assert.equal(dialog.includes('aria-describedby='), true)
    assert.equal(dialog.includes('autoComplete="one-time-code"'), true)
    assert.equal(dialog.includes('aria-live'), true)
    assert.equal(dialog.includes('aria-busy'), true)
    assert.equal(dialog.includes('focus()'), true)
    assert.equal(dialog.includes("key === \"Escape\""), true)
    assert.equal(dialog.includes('min-h-11'), true)
    assert.equal(dialog.includes('Bitte warten…'), true)
    assert.equal(dialog.includes('data-mfa-step-up-lage'), true)
  })

  test('keine Raw-Fehler, IDs, OTP oder Secret-Logs', () => {
    assert.equal(mfa.includes('err.message'), false)
    assert.equal(mfa.includes('err?.message'), false)
    assert.equal(dialog.includes('err.message'), false)
    assert.equal(dialog.includes('zielFaktorId'), false)
    assert.equal(dialog.includes('challengeId'), false)
    assert.equal(dialog.includes('factorId'), false)
    assert.equal(dialog.includes('console.log'), false)
    assert.equal(mfa.includes('console.log'), false)
    assert.equal(logik.includes('console.log'), false)
    assert.equal(logik.includes('service_role'), false)
    assert.equal(mfa.includes('createAdminClient'), false)
    assert.equal(seite.includes('listSessions'), false)
  })

  test('kein globales Consumer-AAL2 und keine Auth-Config-Änderung', () => {
    assert.equal(proxy.includes("currentLevel === 'aal2'"), false)
    assert.match(config, /enroll_enabled\s*=\s*true/)
    assert.equal(logik.includes('Consumer-AAL2'), true)
    assert.equal(mfa.includes('globales Consumer-AAL2'), true)
    assert.equal(logik.includes('keine globale Zwei-Faktor-Pflicht'), true)
    assert.equal(logik.includes('technisch auf die Zwei-Faktor-Stufe'), true)
    assert.equal(dialog.includes('MFA_STEP_UP_DIALOG_TEXT'), true)
  })
})
